version: '3.8'


services:

  mongo-db:
    image: mongo:6.0.6
    restart: always
    environment:
<<<<<<< HEAD
      MONGO_INITDB_ROOT_USERNAME: mongo-user
=======
      MONGO_INITDB_ROOT_USERNAME: mongo-tuta
>>>>>>> cffad1f (Git repo)
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017